config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'movies#home'
  get 'movies', to: 'movies#home'
  get 'movies/list/new', to: 'lists#new'
  get 'lists/:id', to: 'lists#show', as: :list
  post 'lists', to: 'lists#create'
  get 'lists', to: 'movies#home'
  get 'bookmark/new', to: 'bookmarks#new'
  post 'lists/:id/bookmarks', to: 'bookmarks#create', as: :list_bookmarks
  delete 'lists/:list_id/movies/:id', to: 'movies#destroy', as: :remove_movie
  delete 'lists/:id', to: 'lists#destroy'
  post 'lists/:id/reviews', to: 'reviews#create', as: :list_reviews
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: :list_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
  end

  def create
    # raise
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:id])
    @bookmark.list = @list
    @bookmark.save!
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to movies_path
  end

  def show
    @list = List.find(params[:id])
    @reviews = @list.reviews
    @movies = @list.movies
    @bookmark = Bookmark.new
    @review = Review.new
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to movies_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def home
    @lists = List.all
  end

  def index
  end

  def destroy
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.find_by(movie_id: params[:id], list_id: params[:list_id])
    @bookmark.destroy
    redirect_to list_path(@list)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(review_params)
    @list = List.find(params[:id])
    @review.list = @list
    @review.save
    redirect_to list_path(@list)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/new.html.erb
<div class="mdnavbar">
  <div class="d-flex justify-content-between">
    <%= image_tag "popcorn-logo.png", width: 30, class:"m-2" %>
    <div class="action d-flex ">
      <%= link_to "My List", movies_path, class:"btn btn-outline-success"%>
      <%= link_to "New List", movies_list_new_path, class:"btn btn-outline-success"%>
    </div>
  </div>
</div>

<h1>Create list</h1>
<div class="container">
  <%= simple_form_for @list do |f|%>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class:"btn btn-outline-success" %>
    <%= link_to "Back", movies_path, class:"btn btn-sencondary"%>
    <%# <%= button_tag 'Close', type: 'button', action:"moives_path" class:"btn btn-outline-sencondary"%>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="mdnavbar">
  <div class="d-flex justify-content-between">
    <%= image_tag "popcorn-logo.png", width: 30, class:"m-2" %>
    <div class="action d-flex  ">
      <%= link_to "My List", movies_path, class:"btn btn-outline-success"%>
      <%= link_to "New List", movies_list_new_path, class:"btn btn-outline-success"%>
    </div>
  </div>
</div>
<div class="banner">
  <div class="container text-center">
    <h1><%= @list.name %></h1>
  </div>
</div>
<%#  %>

<div class="d-flex justify-content-end mt-3">
  <%= link_to "Add a movie", bookmark_new_path, class:"btn btn-outline-success", "data-bs-toggle": "modal", "data-bs-target": "#staticBackdrop"%>
  <%= link_to "Delete this list", list_path(@list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?" }, class:"btn btn-outline-secondary"%>
</div>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Add a movie to your <%= @list.name %> list</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :movie_id, collection: Movie.all%>
          <%= f.input :comment %>
          <%= f.submit class: "btn btn-success"%>
          <%= button_tag 'Close', type: 'button', data: { bs_dismiss: "modal" }, class: "btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Movies -->
<div class="cards pb-3 mt-3 border-bottom">
  <% @movies.each do |movie| %>
  <div class="card d-flex">
    <div>
      <img class="list-imags" src=<%= movie.poster_url %> width=400px>
      <p class="bolder">Name: <%= movie.title %></p>
      <p class="fz-6">Rating: <%= movie.rating %></p>
      <p class="fst-italic">Overview: <%= movie.overview %></p>
    </div>
    <div class="d-flex justify-content-between">
      <p>✦ <%= Bookmark.where(movie_id: movie.id, list_id: @list.id)[0].comment %></p>
      <%= link_to "delete", remove_movie_path(@list, movie), data: {turbo_method: :delete, turbo_confirm: "Are you sure?" }%>
    </div>
  </div>
  <% end %>
</div>

<!-- Reviews -->
<div class="d-flex justify-content-between mb-5 m-3">
  <div id="reviews">
    <h3>Reviews</h3>
    <% if @reviews.length > 0 %>
      <% @reviews.each do |review| %>
        <p><%= '⭐️' * review.rating %>  <%= review.content.capitalize %></p>
      <% end %>
    <% else %>
      <p>Be the first one to review this list!</p>
    <% end %>
  </div>
  <div id="add-review">
    <%= simple_form_for [@list, @review] do |f| %>
      <%= f.input :content %>
      <select name="review[rating]" id="">
        <option value=1>1</option>
        <option value=2>2</option>
        <option value=3>3</option>
        <option value="4">4</option>
        <option value="5">5</option>
      </select>
      <span>⭐️</span>
      <%= f.submit class: "btn btn-success"%>
    <% end %>
  </div>
</div>

app/views/movies/home.html.erb
<div class="mdnavbar">
  <div class="d-flex justify-content-between">
    <%= image_tag "popcorn-logo.png", width: 30, class:"m-2" %>
    <div class="d-flex align-middle text-center">
      <%= link_to "My List", movies_path, class:"btn btn-outline-success"%>
      <%= link_to "New List", movies_list_new_path, class:"btn btn-outline-success"%>
    </div>
  </div>
</div>

<div class="banner">
  <div class="container text-center">
    <h1>Save any kind of movies</h1>
  </div>
</div>
<div class="list d-flex justify-content-between my-2">
  <h4>My Lists</h4>
  <%= link_to "Create a movie list", movies_list_new_path, class:"btn btn-outline-success"%>
</div>

<div class="cards">
  <% @lists.each do |list|%>
  <div class="card-category"  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>'); height:200px;">
    <%= link_to list.name, list_path(list)%>
  </div>
  <% end %>
</div>